name: Lint, Test and Check formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ steps.setver.outputs.python-version }}
    steps:
      - id: setver
        run: echo "python-version=3.10" >> $GITHUB_OUTPUT

  # LINTING

  ruff_lint:
    name: Ruff (Lint)
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "3.10"

      - name: Install dependencies
        run: |
          uv sync --group dev

      - name: Run Ruff linter
        run: uv run ruff check src/pimpmyrice tests

  mypy:
    name: Mypy
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "3.10"

      - name: Install dependencies
        run: |
          uv sync --group dev

      - name: Run Mypy type checks
        run: uv run mypy src/pimpmyrice tests

  # TESTING

  pytest:
    name: Pytest
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "3.10"

      - name: Install dependencies
        run: |
          uv sync --group dev

      - name: Run Pytest
        run: |
          mkdir -p reports
          uv run pytest --junitxml=reports/test-results.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: reports/test-results.xml

  # FORMATTING

  ruff_format:
    name: Ruff (Format Check)
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "3.10"

      - name: Install dependencies
        run: |
          uv sync --group dev

      - name: Check code format with Ruff
        run: uv run ruff format --check --diff src/pimpmyrice tests

  isort:
    name: Isort
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "3.10"

      - name: Install dependencies
        run: |
          uv sync --group dev

      - name: Check imports with Isort
        run: uv run isort --check --diff src/pimpmyrice tests
